import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/context/AuthProvider";
import {Toaster} from "@/components/ui/sonner";
import Script from "next/script"
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {GoogleOAuthProvider} from "@react-oauth/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Analytity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
            <script defer
                    data-website-id="0fc0774d-93c5-408f-a120-562936a67bc6"
                    data-domain="https://localhost:3000"
                    src="http://localhost:3000/analytics.js">
            </script>
        </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}
      >
      <AuthProvider>
          <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!} >

              {children}
              <Footer/>
          </GoogleOAuthProvider>
      </AuthProvider>
       <Toaster/>
      </body>
    </html>
  );
}
