import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/context/AuthProvider";
import {Toaster} from "@/components/ui/sonner";
import Script from "next/script"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Analytity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
            <script defer
                    data-website-id="b12e8a7e-40f8-428a-975c-f340cb73a61a"
                    data-domain="https://localhost:3000"
                    src="http://localhost:3000/analytics.js">
            </script>
        </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
          {children}
      </AuthProvider>
       <Toaster/>
      </body>
    </html>
  );
}
